### ISSUE TITLE
Extension not working in 2.1.2

### ISSUE THREAD

**Issue by davidkdb** [graphql-dotnet/graphql-client#187] opened 2020-03-11 21:41 UTC
Hi

The Extension status that worked in 2.0.0, gives an error when results is returned with an error, for example if throttled. If no error then Extensions work. We are using it against Shopify:

`   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadToken(JToken token)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadDictionary[TDictionary](JToken element)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadToken(JToken token)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadDictionary[TDictionary](JToken element)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadJson(JsonReader reader, Type objectType, GraphQLExtensionsType existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer.DeserializeFromUtf8Stream[T](Stream stream)
   at GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer.DeserializeFromUtf8StreamAsync[TResponse](Stream stream, CancellationToken cancellationToken)
   at GraphQL.Client.Http.GraphQLHttpClient.<SendHttpPostRequestAsync>d__26`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LibShopify.CommonShopify.<GetDataAsync>d__11`1.MoveNext() in L:\Div\iGroupy\iGroupy\ShopifyQueries.cs:line 730`

**Comment by rose-a** [comment] 2020-03-12 19:27
Could you please provide the incriminating JSON content?

**Comment by davidkdb** [comment] 2020-03-12 22:16
Has nothing to do with the JSON content.

I'm using this call:

retGraphQL = await client.SendQueryAsync<T>(reqGraphQL).ConfigureAwait(false);

It works perfectly unless there is an error returned. In our case the JSON is not faulty, but when throttling it fails with the error stack mentioned above. It should have given the error in the Error, and then Extensions will show the status. So it seems that the Extension parser is the problem. Not a problem in 2.0.0

**Comment by rose-a** [comment] 2020-03-12 22:22
Yes, but I need the complete JSON which is returned from the server (including those errors containing the extensions which fail to parse) so I may enquire why the parser gets hickups with it...

The C# type of the `Extensions` property changed from 2.0.0 to 2.1.0 with the introduction of separate JSON serializers, so its quite likely you hit a case where the transform does not work as intended, and I'd like to fix that (for both available serializers)!

**Comment by davidkdb** [comment] 2020-03-12 22:31
How can I get the returned JSON ? It fails before JSON is returned.

I found out another thing. If the error is in GraphQL syntax, or cost too high then it will work. it's only when the server gives back a status of throtteling it fails. I know this because I was able to provoke throtteling. If not htrotteling, it gives correct error.

**Comment by davidkdb** [comment] 2020-03-12 22:36
I managed to provoke it GraphiQL:

{
  "errors": [
    {
      "message": "Throttled",
      "extensions": {
        "code": "THROTTLED",
        "documentation": "https://help.shopify.com/api/graphql-admin-api/graphql-admin-api-rate-limits"
      }
    }
  ],
  "extensions": {
    "cost": {
      "requestedQueryCost": 992,
      "actualQueryCost": null,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 632,
        "restoreRate": 50
      }
    }
  }
}

**Comment by davidkdb** [comment] 2020-03-15 08:31
Any news on this ?

**Comment by rose-a** [comment] 2020-03-15 08:54
You omitted the actual exception which is thrown in your original post (there's just the stack trace)...

What exception do you get... I suspect it breaks on the `null` field in the extension data...

**Comment by rose-a** [comment] 2020-03-15 09:49
Was able to reproduce this in a test, it's a bug in the `GraphQLExtensionsConverter` for Newtonsoft.

Will be fixed in the next release, meanwhile you can use the provided System.Text.Json serializer, this is not affected by this bug...

**Closed** 2020-03-15 10:12 UTC
