### ISSUE TITLE
GetDataFieldAs doesn't use JsonSerializationSettings

### ISSUE THREAD

**Issue by ullmark** [graphql-dotnet/graphql-client#107] opened 2019-04-26 07:42 UTC
I encountered this issue while using the graphql-client. I (wrongfully?) assumed that assigning a `JsonSerializerSettings` to the `GraphQLHttpClientOptions` would affect how `GetDataFieldAs` worked but it only seemed to affect how the request was serialized. 

If that's infact an issue, I could attempt writing a pull request to fix it.

**Comment by pikax** [comment] 2019-05-06 07:56
Can you provide an sample? 

I think where the problem is an I can create a PR

**Comment by ullmark** [comment] 2019-05-07 06:43
@pikax Yes, well.. the issue is that this line; https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Common/Response/GraphQLResponse.cs#L34 doesn't pass the serializer to the `ToObject<Type>()` call. 

I'll submit a PR.

**Comment by deinok** [comment] 2019-09-16 02:56
As GetDataFieldAs will be deleted from the API i'm going to close this

**Closed by deinok** 2019-09-16 02:56 UTC
