### ISSUE TITLE
Not possible to read HttpResponseMessage in case of AggregateException

### ISSUE THREAD

**Issue by rlipovski** [graphql-dotnet/graphql-client#87] opened 2018-12-13 14:40 UTC
I'm having a hard time to read the Content from the HttpResponseMessage inside the GraphQLHttpException. The code is throwing AggregateException, which holds the InnerExceptions property of type GraphQLHttpException. When I try to read the Content to figure out why my request is not working .net says the object has been disposed respectively, which is also ok as the client is implemented as a singleton. Why singleton? As far as I understood tthe graphql-client is a wrapper around HttpClient, which should be instantiated as singletons due to some internal bug(s). 

This is what I tried, but no results:

            try
            {

                var request = new GraphQLRequest()
                {
                    Query = CreateQuery(query)
                };

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer","token_goes_here");
                client.Options = new GraphQLClientOptions()
                {
                    MediaType = new MediaTypeHeaderValue("application/json"),
                    EndPoint = new Uri(listingImagesGraphqlUrl, UriKind.Absolute)
                };
                var result = client.PostAsync(request).Result;

                if (result.Errors.Any())
                {
                    var unprocessedIds = result.Errors.Select(x => x.AdditonalEntries)
                        .Where(y => y.ContainsKey("extensions")).Where(z => z.ContainsKey("unprocessedIds"));
                }

            }
            catch (AggregateException exception)
            {
                Logging.WriteError(exception);
                var ex = (GraphQLHttpException) exception.InnerExceptions[0];
                Console.WriteLine(ex.HttpResponseMessage.Content.ReadAsStringAsync());
                throw;
            }

Is it possible to read the response body somehow?

**Comment by deinok** [comment] 2018-12-15 21:49
Yes, you are right, the problem is that the `Content` is disposed before the object is passed to the Exception.
So, Console.WriteLine(ex.HttpResponseMessage.Content.ReadAsStringAsync()); will fail cause Content is in disposed state

**Comment by CyrilleFormont** [comment] 2019-04-25 23:56
Any news about this issue ?

**Comment by RobinHSanner** [comment] 2020-03-04 20:20
This issue is pretty critical because if I can't see the error that occurred then i'm totally in the dark about how to fix it.  The issue could be resolved using the Changes:

![Capture](https://user-images.githubusercontent.com/9288083/75919414-83704880-5e2b-11ea-8bfa-ec661a7a1961.PNG)
![Capture2](https://user-images.githubusercontent.com/9288083/75919416-83704880-5e2b-11ea-85e2-2979dd950cd7.PNG)

**Comment by RobinHSanner** [comment] 2020-03-27 17:50
Is this issue fixed in the latest release (3.0.1)?

**Comment by DanielStout5** [comment] 2020-04-02 19:53
The issue is still present in 3.0.1

**Comment by brvaland** [comment] 2020-04-09 09:26
@deinok - any update when a fix will be available or a workaround?

**Comment by rose-a** [comment] 2020-04-09 18:56
What about using [HttpResponseMessage.EnsureSuccessStatusCode](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode?view=netframework-4.8#System_Net_Http_HttpResponseMessage_EnsureSuccessStatusCode) to throw a [HttpRequestException](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httprequestexception?view=netframework-4.8) instead of a `GraphQLHttpException`? MS might have been there before...

I'll try to change this in 3.0.2...

**Comment by RobinHSanner** [comment] 2020-04-09 18:57
Well I had the fix in my response from Mar 4 but the images are gone from the server now and I didn't keep them

**Comment by rose-a** [comment] 2020-04-09 18:59
Yes, I still can see them, but why reinvent the wheel?

**Comment by brvaland** [comment] 2020-04-09 19:06
@rose-a - Thanks for quick reply. Do you have ETA when 3.0.2 will be available so we can test it ?

**Comment by RobinHSanner** [comment] 2020-04-09 19:12
It wasn't a reinvent, the current implementation was broken to such an extent that changing the implementation would have no impact on existing code because the current implementation was not usable.

**Comment by RobinHSanner** [comment] 2020-04-09 19:13
But regardless I'd just be happy to have it resolved, however that is.  Thank you

**Comment by rose-a** [comment] 2020-04-16 21:50
V3.0.2 is out, the client now throws a genuine [HttpRequestException](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httprequestexception?view=netframework-4.8).

**Comment by brvaland** [comment] 2020-04-17 09:53
I have tested v3.0.2 but HttpRequestException does not have any response content. Also the status code is now part of the message string. Can you please explain how we can get the content of api response ?

Is it possible to throw GraphQLHttpException and fill in HttpResponseMessage with missing details.

**Comment by willyt150** [comment] 2020-04-17 17:00
Agree w/ @brvaland we'd like to handle/do different things based on the content of the Graph QL exception, just throwing the exception does allow for that to happen.

**Comment by rose-a** [comment] 2020-04-17 18:13
Maybe a dumb question, but what "non-success" status codes are causing that exception in your cases?

What content are you expecting when you get a bad status code? In my impression GraphQL-related errors (which would be part of the content) should not cause a bad HTTP status code!

**Comment by RobinHSanner** [comment] 2020-04-17 18:18
Well HttpRequestException occurs because of some nonsuccess HttpStatusCode.  It would be nice to have access to that status code without having to try to do string scraping.  Also a failed request usually has some string content in the response that gives you more detail on the error that occurred.

**Comment by RobinHSanner** [comment] 2020-04-17 18:21
Retry logic is a good example, some HttpStatusCodes mean you could maybe do retries and have it end up being successful.

**Comment by RobinHSanner** [comment] 2020-04-17 18:23
I noticed that the GraphQL client does retries but it doesn't do them correctly, i.e. whether to retry or not depends on the returned status code.  For a NotFound and BadRequest both it just keeps retrying but that's a different issue.

**Comment by brvaland** [comment] 2020-04-17 18:23
@rose-a Agree w/ @RobinHSanner we would like to take action based on the returned content string or log the information for investigation.

**Closed** 2020-04-18 22:28 UTC
